/*
   This file was generated automatically by the Mojo IDE version B1.2.3.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     SIZE = 8
     DIV = 6
     TOP = 8b11111111
     UP = 1
*/
module special_counter_4 (
    input clk,
    input rst,
    input ok,
    input inc,
    output reg [7:0] value,
    output reg full
  );
  
  localparam SIZE = 4'h8;
  localparam DIV = 3'h6;
  localparam TOP = 8'hff;
  localparam UP = 1'h1;
  
  
  reg [13:0] M_ctr_d, M_ctr_q = 1'h0;
  
  localparam MAX_VALUE = 14'h3fff;
  
  always @* begin
    M_ctr_d = M_ctr_q;
    
    value = M_ctr_q[6+7-:8];
    if (1'h1) begin
      if (inc && ok) begin
        if (1'h1 && M_ctr_q == 14'h3fff) begin
          M_ctr_d = 1'h0;
          full = 1'h1;
        end else begin
          M_ctr_d = M_ctr_q + 1'h1;
          full = 1'h0;
        end
      end
    end else begin
      M_ctr_d = M_ctr_q - 1'h1;
      if (1'h1 && M_ctr_q == 1'h0) begin
        M_ctr_d = 14'h3fff;
      end
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_ctr_q <= 1'h0;
    end else begin
      M_ctr_q <= M_ctr_d;
    end
  end
  
endmodule
