/*
   This file was generated automatically by the Mojo IDE version B1.2.2.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module switchbox_2 (
    input toggle,
    input clk,
    input rst,
    output reg out
  );
  
  
  wire [1-1:0] M_edge_detector_out;
  reg [1-1:0] M_edge_detector_in;
  edge_detector_3 edge_detector(
    .clk(clk),
    .in(M_edge_detector_in),
    .out(M_edge_detector_out)
  );
  wire [1-1:0] M_button_cond_out;
  reg [1-1:0] M_button_cond_in;
  button_conditioner_4 button_cond(
    .clk(clk),
    .in(M_button_cond_in),
    .out(M_button_cond_out)
  );
  localparam ON_state = 2'd0;
  localparam OFF_state = 2'd1;
  
  reg [1:0] M_state_d, M_state_q = OFF_state;
  
  always @* begin
    M_state_d = M_state_q;
    
    M_button_cond_in = toggle;
    M_edge_detector_in = M_button_cond_out;
    
    case (M_state_q)
      ON_state: begin
        if (M_edge_detector_out) begin
          out = 1'h0;
          M_state_d = OFF_state;
        end else begin
          out = 1'h1;
        end
      end
      OFF_state: begin
        if (M_edge_detector_out) begin
          out = 1'h1;
          M_state_d = ON_state;
        end else begin
          out = 1'h0;
        end
      end
    endcase
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_state_q <= 1'h1;
    end else begin
      M_state_q <= M_state_d;
    end
  end
  
endmodule
