/*
   This file was generated automatically by the Mojo IDE version B1.2.3.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module adder4bit_6 (
    input [3:0] in1,
    input [3:0] in2,
    output reg [4:0] out
  );
  
  
  
  always @* begin
    out = in1 + in2;
  end
endmodule
