/*
   This file was generated automatically by the Mojo IDE version B1.2.3.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

module test_generator_7 (
    input [7:0] value,
    output reg [3:0] out1,
    output reg [3:0] out2
  );
  
  
  
  always @* begin
    out1 = value[0+3-:4];
    out2 = value[4+3-:4];
  end
endmodule
