/*
   This file was generated automatically by the Mojo IDE version B1.2.3.
   Do not edit this file directly. Instead edit the original Lucid source.
   This is a temporary file and any changes made to it will be destroyed.
*/

/*
   Parameters:
     CTR_LEN = 25
*/
module wave_5 (
    input clk,
    input rst,
    output reg [7:0] out
  );
  
  localparam CTR_LEN = 5'h19;
  
  
  reg [24:0] M_ctr_d, M_ctr_q = 1'h0;
  
  integer i;
  
  reg [7:0] acmp;
  
  reg [8:0] result;
  
  always @* begin
    M_ctr_d = M_ctr_q;
    
    M_ctr_d = M_ctr_q + 1'h1;
    for (i = 1'h0; i < 4'h8; i = i + 1) begin
      result = M_ctr_q[16+8-:9] + i * 8'h40;
      if (result[8+0-:1]) begin
        acmp = ~result[0+7-:8];
      end else begin
        acmp = result[0+7-:8];
      end
      out[(i)*1+0-:1] = acmp > M_ctr_q[0+7-:8];
    end
  end
  
  always @(posedge clk) begin
    if (rst == 1'b1) begin
      M_ctr_q <= 1'h0;
    end else begin
      M_ctr_q <= M_ctr_d;
    end
  end
  
endmodule
